### PR TITLE
Namespace oc commands

### PR DESCRIPTION
**Pull request by aidenkeating**

### CODE REVIEW

**Comment by aidenkeating** [comment]
@maleck13 @philbrookes Mind taking a look?

**Comment by aidenkeating** [comment]
@philbrookes This commit (https://github.com/feedhenry/aerogear-digger-apb/pull/17/commits/76d32912c2b274ac21bdfb714c96afe2a6d0ab95) has the changes for using fixed image tags. Tested Mobile CI/CD out and everything works fine.

**Comment by matzew** [comment]
@aidenkeating you mind doing a rebase ?

**Comment by aidenkeating** [comment]
@matzew Rebased

**Pull request merged**
